# Generated by Django 2.0.4 on 2018-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
