# Generated by Django 2.0.4 on 2018-07-29 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pubg_stats', '0003_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePubgModel',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='basepubgmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pubg_stats.BasePubgModel'),
            preserve_default=False,
        ),
    ]
