# Generated by Django 2.0.4 on 2018-07-29 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pubg_stats', '0004_auto_20180729_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.AddField(
            model_name='season',
            name='basepubgmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pubg_stats.BasePubgModel'),
            preserve_default=False,
        ),
    ]
